# Generated by Django 2.0.3 on 2018-08-06 01:32

import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion
import drf_chunked_upload.models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exampendingrequestvideo',
            name='file_upload',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos', to='api.FileUpload'),
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='file',
            field=models.FileField(max_length=255, null=True, storage=django.core.files.storage.FileSystemStorage(), upload_to=drf_chunked_upload.models.generate_filename),
        ),
    ]
