# Generated by Django 2.0.3 on 2018-07-29 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exampendingrequest',
            name='duration',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
