# Generated by Django 2.0.3 on 2018-09-04 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='shared_with_devices',
            field=models.ManyToManyField(blank=True, related_name='allowed_shared_exercises', to='api.Device'),
        ),
    ]
