# Generated by Django 2.0.3 on 2018-08-02 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Guest'), (1, 'Student'), (2, 'Teacher'), (3, 'Supervisor')], null=True),
        ),
    ]
