# Generated by Django 2.0.3 on 2019-03-12 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='daily_repetitions',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='practice_days',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
