# Generated by Django 2.0.3 on 2018-08-06 03:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180806_0132'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='video_shares',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='video',
            name='views',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
