# Generated by Django 2.0.3 on 2018-07-12 23:25

from django.db import migrations, models
import storages.backends.gcloud


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180712_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='file',
            field=models.FileField(storage=storages.backends.gcloud.GoogleCloudStorage(bucket_name='psq_videos'), upload_to='videos'),
        ),
    ]
