# Generated by Django 2.0.3 on 2018-06-04 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180604_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='friendly_name',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
