# Generated by Django 2.0.3 on 2018-07-29 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_exampendingrequest_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='created_from_tutorial',
        ),
        migrations.AddField(
            model_name='exercise',
            name='tutorials',
            field=models.ManyToManyField(blank=True, related_name='related_exercises', to='api.Exercise'),
        ),
    ]
