# Generated by Django 2.0.3 on 2018-08-06 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20180806_0308'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='video_views',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
