# Generated by Django 2.0.3 on 2018-08-08 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_exam_video_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='locale',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Spanish'), (2, 'English')], default=1, null=True),
        ),
    ]
