# Generated by Django 2.0.3 on 2018-08-09 01:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_user_locale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='serial',
            field=models.CharField(default=uuid.uuid4, max_length=255, unique=True),
        ),
    ]
